//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class amca_website_aeEntities1 : DbContext
{
    public amca_website_aeEntities1()
        : base("name=amca_website_aeEntities1")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<BlogComment> BlogComments { get; set; }
    public virtual DbSet<ContactUsData> ContactUsDatas { get; set; }
    public virtual DbSet<WebsiteLead> WebsiteLeads { get; set; }
    public virtual DbSet<Service> Services { get; set; }

    public virtual int ProcBlogComments(Nullable<int> autoId, string username, string useremail, string userwebsite, string usercomment)
    {
        var autoIdParameter = autoId.HasValue ?
            new ObjectParameter("AutoId", autoId) :
            new ObjectParameter("AutoId", typeof(int));

        var usernameParameter = username != null ?
            new ObjectParameter("Username", username) :
            new ObjectParameter("Username", typeof(string));

        var useremailParameter = useremail != null ?
            new ObjectParameter("Useremail", useremail) :
            new ObjectParameter("Useremail", typeof(string));

        var userwebsiteParameter = userwebsite != null ?
            new ObjectParameter("Userwebsite", userwebsite) :
            new ObjectParameter("Userwebsite", typeof(string));

        var usercommentParameter = usercomment != null ?
            new ObjectParameter("Usercomment", usercomment) :
            new ObjectParameter("Usercomment", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcBlogComments", autoIdParameter, usernameParameter, useremailParameter, userwebsiteParameter, usercommentParameter);
    }

    public virtual int ProcContactLeadData(Nullable<int> autoId, string nameContact, string emailContact, string countryCodeContact, string mobileContact, string messageContact)
    {
        var autoIdParameter = autoId.HasValue ?
            new ObjectParameter("AutoId", autoId) :
            new ObjectParameter("AutoId", typeof(int));

        var nameContactParameter = nameContact != null ?
            new ObjectParameter("NameContact", nameContact) :
            new ObjectParameter("NameContact", typeof(string));

        var emailContactParameter = emailContact != null ?
            new ObjectParameter("EmailContact", emailContact) :
            new ObjectParameter("EmailContact", typeof(string));

        var countryCodeContactParameter = countryCodeContact != null ?
            new ObjectParameter("CountryCodeContact", countryCodeContact) :
            new ObjectParameter("CountryCodeContact", typeof(string));

        var mobileContactParameter = mobileContact != null ?
            new ObjectParameter("MobileContact", mobileContact) :
            new ObjectParameter("MobileContact", typeof(string));

        var messageContactParameter = messageContact != null ?
            new ObjectParameter("MessageContact", messageContact) :
            new ObjectParameter("MessageContact", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcContactLeadData", autoIdParameter, nameContactParameter, emailContactParameter, countryCodeContactParameter, mobileContactParameter, messageContactParameter);
    }

    public virtual int WebsiteLeadData(Nullable<int> autoId, string name, string emailId, string countryCode, string phoneNo, string services)
    {
        var autoIdParameter = autoId.HasValue ?
            new ObjectParameter("AutoId", autoId) :
            new ObjectParameter("AutoId", typeof(int));

        var nameParameter = name != null ?
            new ObjectParameter("Name", name) :
            new ObjectParameter("Name", typeof(string));

        var emailIdParameter = emailId != null ?
            new ObjectParameter("EmailId", emailId) :
            new ObjectParameter("EmailId", typeof(string));

        var countryCodeParameter = countryCode != null ?
            new ObjectParameter("CountryCode", countryCode) :
            new ObjectParameter("CountryCode", typeof(string));

        var phoneNoParameter = phoneNo != null ?
            new ObjectParameter("PhoneNo", phoneNo) :
            new ObjectParameter("PhoneNo", typeof(string));

        var servicesParameter = services != null ?
            new ObjectParameter("Services", services) :
            new ObjectParameter("Services", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WebsiteLeadData", autoIdParameter, nameParameter, emailIdParameter, countryCodeParameter, phoneNoParameter, servicesParameter);
    }
}
