//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogComment
    {
        public int AutoId { get; set; }
        public string Username { get; set; }
        public string Useremail { get; set; }
        public string Userwebsite { get; set; }
        public string Usercomment { get; set; }
    }
}
