//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactUsData
    {
        public int AutoId { get; set; }
        public string NameContact { get; set; }
        public string EmailContact { get; set; }
        public string CountryCodeContact { get; set; }
        public string MobileContact { get; set; }
        public string MessageContact { get; set; }
    }
}
