//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteLead
    {
        public int AutoId { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public string CountryCode { get; set; }
        public string PhoneNo { get; set; }
        public string Services { get; set; }
    }
}
